language: python
sudo: required
python:
  - "3.6"
# command to install dependencies
install:
  - bash build_intall.sh
# command to run tests
script:
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source activate intel
  - cd src/cython_files
  - rm -rf build *so cython_integrand.c *html
  - python setup.py build_ext --inplace
  - cd ../..
  - pytest testing/test*.py
